---
- name: Install elasticsearch
  hosts: elasticsearch
  user: ec2-user
  sudo: yes

  roles:
    - common
    - elasticsearch

- name: Install webapp
  hosts: webapp
  user: ec2-user
  sudo: yes

  roles:
    - common
    - kibana
    - nginx
    - kopf